using System.Text;

namespace SiftQL.Generators.Schema;

internal static class FilterSchemaEmitter
{
    public static string Emit(
        EquatableArray<GeneratedSchema> schemas,
        string providerName,
        bool registerProvider)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using SiftQL.Schema;");
        source.AppendLine();
        source.AppendLine("namespace SiftQL;");
        source.AppendLine();
        source.Append("internal static class ");
        source.AppendLine(providerName);
        source.AppendLine("{");
        if (registerProvider && schemas.Count > 0)
            EmitRegistration(source, schemas);
        EmitTryCreate(source, schemas);
        foreach (GeneratedSchema schema in schemas)
            EmitFactory(source, schema);
        source.AppendLine("}");
        return source.ToString();
    }

    private static void EmitRegistration(StringBuilder source, EquatableArray<GeneratedSchema> schemas)
    {
        source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.AppendLine("    internal static void Register()");
        source.AppendLine("    {");
        source.Append("        GeneratedFilterSchemaRegistry.Register(typeof(");
        source.Append(schemas[0].TypeName);
        source.AppendLine(").Assembly, TryCreate);");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void EmitTryCreate(StringBuilder source, EquatableArray<GeneratedSchema> schemas)
    {
        source.AppendLine("    public static bool TryCreate(Type subjectType, out FilterSchema? schema)");
        source.AppendLine("    {");
        foreach (GeneratedSchema schema in schemas)
        {
            source.Append("        if (subjectType == typeof(");
            source.Append(schema.TypeName);
            source.AppendLine("))");
            source.AppendLine("        {");
            source.Append("            schema = Create");
            source.Append(schema.HelperName);
            source.AppendLine("();");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
            source.AppendLine();
        }

        source.AppendLine("        schema = null;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void EmitFactory(StringBuilder source, GeneratedSchema schema)
    {
        source.Append("    private static FilterSchema Create");
        source.Append(schema.HelperName);
        source.AppendLine("() =>");
        source.Append("        GeneratedFilterSchemaRegistry.Create(typeof(");
        source.Append(schema.TypeName);
        source.AppendLine("), new FilterField[]");
        source.AppendLine("        {");
        EmitEventTypeField(source, schema.TypeName);
        EmitEventNameField(source, schema.TypeName);
        foreach (GeneratedField field in schema.Fields)
            EmitField(source, schema, field);
        source.AppendLine("        });");
        source.AppendLine();
    }

    private static void EmitEventTypeField(StringBuilder source, string typeName) =>
        EmitTypeVirtualField(
            source,
            "subjectType",
            "typeof(" + typeName + ").FullName ?? typeof(" + typeName + ").Name");

    private static void EmitEventNameField(StringBuilder source, string typeName) =>
        EmitTypeVirtualField(source, "subjectName", "typeof(" + typeName + ").Name");

    private static void EmitTypeVirtualField(StringBuilder source, string name, string valueExpression)
    {
        source.Append("            new(");
        AppendLiteral(source, name);
        source.Append(", typeof(string), FilterFieldKind.Scalar, static _ => ");
        source.Append(valueExpression);
        source.Append(", new FilterScalarAccessor(FilterScalarKind.String, text: static _ => ");
        source.Append(valueExpression);
        source.Append("), null, static _ => ProjectionValueFactory.FromString(");
        source.Append(valueExpression);
        source.Append("), FilterFieldAccess.ForConstant(");
        source.Append(valueExpression);
        source.AppendLine(")),");
    }

    private static void EmitField(StringBuilder source, GeneratedSchema schema, GeneratedField field)
    {
        string access = CSharpIdentifier.EscapePath(field.Access);
        source.Append("            new(");
        AppendLiteral(source, field.Name);
        source.Append(", typeof(");
        source.Append(field.ValueType);
        source.Append("), FilterFieldKind.");
        source.Append(FieldKindName(field.FieldKind));
        source.Append(", static subject => ((");
        source.Append(schema.TypeName);
        source.Append(")subject).");
        source.Append(access);
        source.Append(", ");
        source.Append(ScalarAccessor(schema, field));
        source.Append(", ");
        source.Append(ArrayAccessor(schema, field));
        source.Append(", ");
        source.Append(ProjectionAccessor(schema, field));
        source.Append(", FilterFieldAccess.ForProperty(");
        AppendLiteral(source, field.Access);
        source.Append(")");
        source.AppendLine("),");
    }

    private static string ScalarAccessor(GeneratedSchema schema, GeneratedField field)
    {
        if (field.FieldKind != GeneratedFieldKind.Scalar || !field.EmitsScalarAccessor)
            return "null";

        string access = "((" + schema.TypeName + ")subject)." + CSharpIdentifier.EscapePath(field.Access);
        return field.ScalarKind switch
        {
            GeneratedScalarKind.Boolean =>
                field.IsNullable
                    ? "new FilterScalarAccessor(FilterScalarKind.Boolean, boolean: static subject => " +
                        NullableValue(field, access, "bool", string.Empty) + ")"
                    : "new FilterScalarAccessor(FilterScalarKind.Boolean, requiredBoolean: static subject => " +
                        access + ")",
            GeneratedScalarKind.Number =>
                field.IsNullable
                    ? "new FilterScalarAccessor(FilterScalarKind.Number, number: static subject => " +
                        NullableValue(field, access, "double", NumberCast(field.ValueType)) + ")"
                    : "new FilterScalarAccessor(FilterScalarKind.Number, requiredNumber: static subject => " +
                        RequiredNumberValue(field.ValueType, access) + ")",
            GeneratedScalarKind.String =>
                "new FilterScalarAccessor(FilterScalarKind.String, text: static subject => " + access + ")",
            GeneratedScalarKind.Guid =>
                field.IsNullable
                    ? "new FilterScalarAccessor(FilterScalarKind.Guid, guid: static subject => " +
                        NullableValue(field, access, "Guid", string.Empty) + ")"
                    : "new FilterScalarAccessor(FilterScalarKind.Guid, requiredGuid: static subject => " +
                        access + ")",
            GeneratedScalarKind.Enum =>
                field.IsNullable
                    ? "new FilterScalarAccessor(FilterScalarKind.Enum, enumeration: static subject => GeneratedFilterSchemaRegistry.NullableEnumToInt64OrNull(" +
                        access + "))"
                    : "new FilterScalarAccessor(FilterScalarKind.Enum, enumeration: static subject => GeneratedFilterSchemaRegistry.EnumToInt64OrNull(" +
                        access + "))",
            _ => "null",
        };
    }

    private static string ArrayAccessor(GeneratedSchema schema, GeneratedField field)
    {
        if (field.FieldKind != GeneratedFieldKind.Array || field.ArrayContainsMethod is null)
            return "null";

        string access = "((" + schema.TypeName + ")subject)." + CSharpIdentifier.EscapePath(field.Access);
        return field.ScalarKind switch
        {
            GeneratedScalarKind.Boolean =>
                "new FilterArrayAccessor(FilterScalarKind.Boolean, booleanContains: static (subject, expected) => " +
                "FilterArrayContains." + field.ArrayContainsMethod + "(" + access + ", expected))",
            GeneratedScalarKind.Number =>
                "new FilterArrayAccessor(FilterScalarKind.Number, numberContains: static (subject, expected) => " +
                "FilterArrayContains." + field.ArrayContainsMethod + "(" + access + ", expected))",
            GeneratedScalarKind.String =>
                "new FilterArrayAccessor(FilterScalarKind.String, textContains: static (subject, expected) => " +
                "FilterArrayContains." + field.ArrayContainsMethod + "(" + access + ", expected))",
            GeneratedScalarKind.Guid =>
                "new FilterArrayAccessor(FilterScalarKind.Guid, guidContains: static (subject, expected) => " +
                "FilterArrayContains." + field.ArrayContainsMethod + "(" + access + ", expected))",
            _ => "null",
        };
    }

    private static string ProjectionAccessor(GeneratedSchema schema, GeneratedField field)
    {
        string access = "((" + schema.TypeName + ")subject)." + CSharpIdentifier.EscapePath(field.Access);
        if (field.FieldKind == GeneratedFieldKind.Object)
            return "static subject => ProjectionValueFactory.FromObject(" + access + ")";
        if (field.FieldKind != GeneratedFieldKind.Scalar)
            return "null";

        return field.ScalarKind == GeneratedScalarKind.Enum
            ? "static subject => ProjectionValueFactory.FromEnum<" + field.ValueType + ">(" + access + ")"
            : ProjectionFactoryMethod(field) is { } method
                ? "static subject => ProjectionValueFactory." + method + "(" + access + ")"
                : "null";
    }

    private static string? ProjectionFactoryMethod(GeneratedField field) =>
        field.ScalarKind switch
        {
            GeneratedScalarKind.Boolean => "FromBoolean",
            GeneratedScalarKind.String => "FromString",
            GeneratedScalarKind.Guid => "FromGuid",
            GeneratedScalarKind.Number => NormalizeTypeName(field.ValueType) switch
            {
                "byte" => "FromByte",
                "sbyte" => "FromSByte",
                "short" => "FromInt16",
                "ushort" => "FromUInt16",
                "int" => "FromInt32",
                "uint" => "FromUInt32",
                "long" => "FromInt64",
                "ulong" => "FromUInt64",
                "float" => "FromSingle",
                "double" => "FromDouble",
                "decimal" => "FromDecimal",
                _ => null,
            },
            _ => null,
        };

    private static string FieldKindName(GeneratedFieldKind kind) =>
        kind switch
        {
            GeneratedFieldKind.Scalar => "Scalar",
            GeneratedFieldKind.Array => "Array",
            GeneratedFieldKind.Object => "Object",
            _ => "Scalar",
        };

    private static string NormalizeTypeName(string typeName) =>
        typeName switch
        {
            "global::System.Byte" => "byte",
            "global::System.SByte" => "sbyte",
            "global::System.Int16" => "short",
            "global::System.UInt16" => "ushort",
            "global::System.Int32" => "int",
            "global::System.UInt32" => "uint",
            "global::System.Int64" => "long",
            "global::System.UInt64" => "ulong",
            "global::System.Single" => "float",
            "global::System.Double" => "double",
            "global::System.Decimal" => "decimal",
            _ => typeName,
        };

    private static string NullableValue(GeneratedField field, string access, string nullableType, string cast)
    {
        string value = string.IsNullOrEmpty(cast) ? access : cast + access + ")";
        if (!field.IsNullable)
            return "(" + nullableType + "?)" + value;

        string nullableValue = string.IsNullOrEmpty(cast)
            ? access + ".GetValueOrDefault()"
            : cast + access + ".GetValueOrDefault())";
        return access + ".HasValue ? (" + nullableType + "?)" + nullableValue + " : null";
    }

    private static string NumberCast(string valueType) =>
        valueType == "decimal" || valueType == "global::System.Decimal" ? "(double)(" : string.Empty;

    private static string RequiredNumberValue(string valueType, string access)
    {
        string cast = NumberCast(valueType);
        return string.IsNullOrEmpty(cast) ? access : cast + access + ")";
    }

    private static void AppendLiteral(StringBuilder source, string value)
    {
        CSharpStringLiteral.AppendTo(source, value);
    }
}
