<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ShaRPC" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\SiftQL\SiftQL.csproj" />
    <ProjectReference Include="..\Client\Client.csproj"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
    <ProjectReference Include="..\SharedContracts\SharedContracts.csproj" />
  </ItemGroup>

</Project>
