<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>SiftQL</AssemblyName>
    <RootNamespace>SiftQL</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.5.187" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SiftQL.Abstractions\SiftQL.Abstractions.csproj" />
    <ProjectReference Include="..\SiftQL.Generators\SiftQL.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

</Project>
