<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>SiftQL</AssemblyName>
    <RootNamespace>SiftQL</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.5.187" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SiftQL.Abstractions\SiftQL.Abstractions.csproj" />
    <ProjectReference Include="..\SiftQL.Generators\SiftQL.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\SiftQL.Generators\bin\$(Configuration)\netstandard2.0\SiftQL.Generators.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="..\SiftQL.Generators\bin\$(Configuration)\netstandard2.0\System.Text.Json.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
  </ItemGroup>

</Project>
