using System.Globalization;
using System.Text;

namespace SiftQL.Generators.Hot;

internal static class HotProviderEmitter
{
    public static string Emit(HotProviderSource provider)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine("using System.Runtime.CompilerServices;");
        source.AppendLine("using SiftQL;");
        source.AppendLine("using SiftQL.Expressions;");
        source.AppendLine("using SiftQL.Hot;");
        source.AppendLine("using SiftQL.Projected;");
        source.AppendLine("using SiftQL.Projection;");
        source.AppendLine("using SiftQL.Schema;");
        source.AppendLine("using SiftQL.Values;");
        source.AppendLine();
        EmitAssemblyMetadata(source, provider);
        source.AppendLine();
        source.AppendLine("namespace SiftQL.Hot.Generated;");
        source.AppendLine();
        source.Append("internal sealed partial class ").Append(provider.ProviderName).AppendLine(" : IPrecompiledTieredProvider");
        source.AppendLine("{");
        HotProviderLookupEmitter.Emit(source, provider);
        for (int i = 0; i < provider.Entries.Count; i++)
            EmitEntry(source, provider.Entries[i], i);
        HotProviderRuntimeEmitter.EmitHelpers(source);
        source.AppendLine("}");
        source.AppendLine();
        HotProviderRuntimeEmitter.EmitRegistration(source, provider.ProviderName, provider.ManifestHash);
        return source.ToString();
    }

    private static void EmitAssemblyMetadata(StringBuilder source, HotProviderSource provider)
    {
        source.Append("[assembly: System.Reflection.AssemblyMetadata(\"SiftQLHotManifestHash\", ");
        AppendLiteral(source, provider.ManifestHash);
        source.AppendLine(")]");
        source.AppendLine("[assembly: System.Reflection.AssemblyMetadata(\"SiftQLHotManifestSchema\", \"siftql.hot.v1\")]");
        source.AppendLine("[assembly: System.Reflection.AssemblyMetadata(\"SiftQLHotFilterEngine\", \"tiered-v1\")]");
        source.AppendLine("[assembly: System.Reflection.AssemblyMetadata(\"SiftQLHotGenerator\", \"hot-sourcegen-v1\")]");
    }

    private static void EmitEntry(StringBuilder source, HotProviderEntry entry, int index)
    {
        if (entry.Kind == HotEntryKind.Filter && entry.Filter is not null)
            EmitFilter(source, entry, entry.Filter, index);
        if (entry.Kind == HotEntryKind.Projection && entry.Projection is not null)
            EmitProjection(source, entry, entry.Projection, index);
    }

    private static void EmitFilter(StringBuilder source, HotProviderEntry entry, HotFilterNode node, int index)
    {
        var members = new StringBuilder();
        HotFilterParameterMap parameters = HotFilterParameterMap.Create(node);
        int fields = 0;
        int values = 0;
        string body = FilterExpression(members, entry, node, parameters, index, ref fields, ref values);
        source.Append(members);
        source.Append("    private static bool Filter_").Append(index);
        source.Append(parameters.HasParameters
            ? "(object subject, IReadOnlyList<FilterValue> parameters) => "
            : "(object subject) => ");
        source.Append(body).AppendLine(";");
        source.AppendLine();
    }

    private static string FilterExpression(
        StringBuilder members,
        HotProviderEntry entry,
        HotFilterNode node,
        HotFilterParameterMap parameters,
        int index,
        ref int fields,
        ref int values)
    {
        return node.Kind switch
        {
            HotFilterNodeKind.Any => "true",
            HotFilterNodeKind.Compare => "FilterValues.Compare(" + Field(members, entry, node, index, ref fields) +
                ".Getter(subject), " + Value(members, node.Value!, parameters, index, ref values) +
                ", (FilterOperator)" + node.Operator.ToString(CultureInfo.InvariantCulture) +
                (node.IgnoreCase ? ", true)" : ")"),
            HotFilterNodeKind.In => "FilterValues.In(" + Field(members, entry, node, index, ref fields) +
                ".Getter(subject), " + Values(members, node.Values, parameters, index, ref values) + ")",
            HotFilterNodeKind.Exists => Field(members, entry, node, index, ref fields) + ".Getter(subject) is not null",
            HotFilterNodeKind.Contains => "FilterValues.Contains(" + Field(members, entry, node, index, ref fields) +
                ".Getter(subject), " + Value(members, node.Value!, parameters, index, ref values) + ")",
            HotFilterNodeKind.Not => "!(" + FilterExpression(members, entry, node.Children[0], parameters, index, ref fields, ref values) + ")",
            HotFilterNodeKind.And => Composite(members, entry, node, parameters, index, " && ", and: true, ref fields, ref values),
            HotFilterNodeKind.Or => Composite(members, entry, node, parameters, index, " || ", and: false, ref fields, ref values),
            _ => "false",
        };
    }

    private static string Composite(
        StringBuilder members,
        HotProviderEntry entry,
        HotFilterNode node,
        HotFilterParameterMap parameters,
        int index,
        string op,
        bool and,
        ref int fields,
        ref int values)
    {
        HotFilterNode[] children = and && node.Children.Count > 1
            ? node.Children.Items.OrderBy(EstimateCost).ToArray()
            : node.Children.Items.ToArray();
        var parts = new string[children.Length];
        for (int i = 0; i < parts.Length; i++)
            parts[i] = FilterExpression(members, entry, children[i], parameters, index, ref fields, ref values);
        return "(" + string.Join(op, parts) + ")";
    }

    private static int EstimateCost(HotFilterNode node) =>
        node.Kind switch
        {
            HotFilterNodeKind.Any => 0,
            HotFilterNodeKind.Compare => node.Operator == 0 ? 1 : 2,
            HotFilterNodeKind.Exists => 1,
            HotFilterNodeKind.In => 4 + Math.Min(node.Values.Count, 16),
            HotFilterNodeKind.Contains => 32,
            HotFilterNodeKind.Not => 8 + ChildrenCost(node),
            HotFilterNodeKind.And => ChildrenCost(node),
            HotFilterNodeKind.Or => 16 + ChildrenCost(node),
            _ => 64,
        };

    private static int ChildrenCost(HotFilterNode node)
    {
        int cost = 0;
        for (int i = 0; i < node.Children.Count; i++)
            cost += EstimateCost(node.Children[i]);
        return cost;
    }

    private static string Field(
        StringBuilder members,
        HotProviderEntry entry,
        HotFilterNode node,
        int index,
        ref int fields)
    {
        string name = "s_filter_" + index + "_field_" + fields++;
        members.Append("    private static readonly FilterField ").Append(name).Append(" = RequireField(typeof(");
        members.Append(entry.SubjectTypeName).Append("), ");
        AppendLiteral(members, node.Field);
        members.AppendLine(");");
        return name;
    }

    private static string Value(
        StringBuilder members,
        HotFilterValue value,
        HotFilterParameterMap parameters,
        int index,
        ref int values)
    {
        if (!string.IsNullOrWhiteSpace(value.ParameterKey))
        {
            return "Parameter(parameters, " +
                parameters.IndexOf(value).ToString(CultureInfo.InvariantCulture) +
                ")";
        }

        string name = "s_filter_" + index + "_value_" + values++;
        members.Append("    private static readonly FilterValue ").Append(name).Append(" = ");
        HotFilterValueEmitter.Emit(members, value);
        members.AppendLine(";");
        return name;
    }

    private static string Values(
        StringBuilder members,
        EquatableArray<HotFilterValue> items,
        HotFilterParameterMap parameters,
        int index,
        ref int values)
    {
        if (HasParameterValues(items))
            return RuntimeValues(members, items, parameters, index, ref values);

        string name = "s_filter_" + index + "_values_" + values++;
        members.Append("    private static readonly FilterValue[] ").Append(name);
        members.AppendLine(" = new FilterValue[]");
        members.AppendLine("    {");
        for (int i = 0; i < items.Count; i++)
        {
            members.Append("        ");
            HotFilterValueEmitter.Emit(members, items[i]);
            members.AppendLine(",");
        }
        members.AppendLine("    };");
        return name;
    }

    private static bool HasParameterValues(EquatableArray<HotFilterValue> items) =>
        items.Items.Any(static item => !string.IsNullOrWhiteSpace(item.ParameterKey));

    private static string RuntimeValues(
        StringBuilder members,
        EquatableArray<HotFilterValue> items,
        HotFilterParameterMap parameters,
        int index,
        ref int values)
    {
        var source = new StringBuilder("new FilterValue[] { ");
        for (int i = 0; i < items.Count; i++)
        {
            if (i != 0)
                source.Append(", ");
            source.Append(Value(members, items[i], parameters, index, ref values));
        }

        return source.Append(" }").ToString();
    }

    private static void EmitProjection(
        StringBuilder source,
        HotProviderEntry entry,
        HotProjection projection,
        int index)
    {
        for (int i = 0; i < projection.Fields.Count; i++)
        {
            source.Append("    private static readonly FilterField s_projection_").Append(index).Append("_field_");
            source.Append(i).Append(" = RequireField(typeof(").Append(entry.SubjectTypeName).Append("), ");
            AppendLiteral(source, projection.Fields[i].Path);
            source.AppendLine(");");
        }
        source.Append("    private static ProjectedEventField[] Projection_").Append(index);
        source.AppendLine(projection.HasParameters
            ? "(object subject, IReadOnlyList<FilterValue> parameters) =>"
            : "(object subject) =>");
        if (projection.Fields.Count == 0)
        {
            source.AppendLine("        Array.Empty<ProjectedEventField>();");
        }
        else
        {
            source.AppendLine("        new ProjectedEventField[]");
            source.AppendLine("        {");
            for (int i = 0; i < projection.Fields.Count; i++)
            {
                source.Append("            new(");
                AppendLiteral(source, projection.Fields[i].Name);
                source.Append(", Project(s_projection_").Append(index).Append("_field_").Append(i);
                source.AppendLine(", subject)),");
            }
            source.AppendLine("        };");
        }
        source.AppendLine();
    }

    private static void AppendLiteral(StringBuilder source, string value)
    {
        CSharpStringLiteral.AppendTo(source, value);
    }
}
