using System.Text;

namespace SiftQL.Generators.QueryContexts;

internal static class QueryContextEmitter
{
    public static string Emit(QueryContextModel context)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        if (!string.IsNullOrEmpty(context.NamespaceName))
        {
            source.Append("namespace ");
            source.Append(CSharpIdentifier.EscapePath(context.NamespaceName));
            source.AppendLine(";");
            source.AppendLine();
        }

        source.Append("public static class ");
        source.Append(CSharpIdentifier.EscapePath(context.HelperName));
        source.AppendLine();
        source.AppendLine("{");
        EmitConstants(source, context);
        EmitWithContext(source, context);
        foreach (QueryContextMethodModel method in context.Methods)
            EmitIncludeFactory(source, method);
        EmitDescriptor(source, context);
        EmitRegister(source);
        source.AppendLine("}");
        return source.ToString();
    }

    private static void EmitConstants(StringBuilder source, QueryContextModel context)
    {
        source.Append("    public const string ContextId = ");
        CSharpStringLiteral.AppendTo(source, context.ContextId);
        source.AppendLine(";");
        foreach (QueryContextMethodModel method in context.Methods)
        {
            source.Append("    public const string ");
            source.Append(CSharpIdentifier.EscapePath(method.Name + "MethodId"));
            source.Append(" = ");
            CSharpStringLiteral.AppendTo(source, method.MethodId);
            source.AppendLine(";");
        }

        source.AppendLine();
    }

    private static void EmitWithContext(StringBuilder source, QueryContextModel context)
    {
        source.Append("    public static global::SiftQL.QueryKernel<TSubject, ");
        source.Append(context.InterfaceTypeName);
        source.Append("> With");
        string helperBaseName = HelperBaseName(context);
        source.Append(CSharpIdentifier.EscapePath(helperBaseName));
        if (!helperBaseName.EndsWith("Context", StringComparison.Ordinal))
            source.Append("Context");
        source.AppendLine("<TSubject>(");
        source.AppendLine("        this global::SiftQL.QueryKernel<TSubject> kernel)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(kernel);");
        source.AppendLine("        RegisterSiftQueryContexts();");
        source.Append("        return global::SiftQL.QueryKernelContextExtensions.WithContext<TSubject, ");
        source.Append(context.InterfaceTypeName);
        source.AppendLine(">(kernel);");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void EmitIncludeFactory(StringBuilder source, QueryContextMethodModel method)
    {
        source.Append("    public static global::SiftQL.Expressions.EventProjectionInclude ");
        source.Append(CSharpIdentifier.EscapePath(method.Name));
        source.Append('(');
        for (int i = 0; i < method.Parameters.Count; i++)
        {
            if (i > 0)
                source.Append(", ");
            source.Append("global::SiftQL.Expressions.EventProjectionArgument ");
            source.Append(CSharpIdentifier.EscapePath(method.Parameters[i].Name));
        }

        if (method.Parameters.Count > 0)
            source.Append(", ");
        source.Append("string resultName = ");
        CSharpStringLiteral.AppendTo(source, ResultName(method.Name));
        source.AppendLine(", string memberPath = \"\")");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(resultName);");
        source.AppendLine("        return new global::SiftQL.Expressions.EventProjectionInclude(");
        source.AppendLine("            global::SiftQL.Expressions.EventProjectionContextIntrinsics.Method(");
        source.AppendLine("                ContextId,");
        source.Append("                ");
        source.Append(CSharpIdentifier.EscapePath(method.Name + "MethodId"));
        source.AppendLine(",");
        source.AppendLine("                memberPath),");
        source.AppendLine("            resultName");
        foreach (QueryContextParameterModel parameter in method.Parameters)
        {
            source.Append("            , ");
            source.Append(CSharpIdentifier.EscapePath(parameter.Name));
            source.AppendLine();
        }

        source.AppendLine("        );");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void EmitDescriptor(StringBuilder source, QueryContextModel context)
    {
        source.AppendLine("    public static global::SiftQL.SiftQueryContextDescriptor Descriptor { get; } = new(");
        source.Append("        typeof(");
        source.Append(context.InterfaceTypeName);
        source.AppendLine("),");
        source.AppendLine("        ContextId,");
        source.AppendLine("        new global::SiftQL.SiftQueryContextMethodDescriptor[]");
        source.AppendLine("        {");
        foreach (QueryContextMethodModel method in context.Methods)
            EmitMethodDescriptor(source, method);
        source.AppendLine("        });");
        source.AppendLine();
    }

    private static void EmitMethodDescriptor(StringBuilder source, QueryContextMethodModel method)
    {
        source.AppendLine("            new(");
        source.Append("                nameof(");
        source.Append(method.Name);
        source.AppendLine("),");
        source.Append("                ");
        source.Append(CSharpIdentifier.EscapePath(method.Name + "MethodId"));
        source.AppendLine(",");
        source.Append("                typeof(");
        source.Append(method.ReturnTypeName);
        source.AppendLine("),");
        source.AppendLine("                new global::SiftQL.SiftQueryContextParameterDescriptor[]");
        source.AppendLine("                {");
        foreach (QueryContextParameterModel parameter in method.Parameters)
            EmitParameterDescriptor(source, parameter);
        source.AppendLine("                }),");
    }

    private static void EmitParameterDescriptor(StringBuilder source, QueryContextParameterModel parameter)
    {
        source.Append("                    new(");
        CSharpStringLiteral.AppendTo(source, parameter.Name);
        source.Append(", typeof(");
        source.Append(parameter.TypeName);
        source.Append("), ");
        source.Append(parameter.HasDefaultValue ? "true, " : "false, ");
        source.Append(parameter.HasDefaultValue ? parameter.DefaultValueSource : "null");
        source.AppendLine("),");
    }

    private static void EmitRegister(StringBuilder source)
    {
        source.AppendLine("    public static void RegisterSiftQueryContexts() =>");
        source.AppendLine("        global::SiftQL.SiftQueryContextRegistry.Register(Descriptor);");
    }

    private static string ResultName(string methodName) =>
        methodName.Length == 0
            ? "context"
            : char.ToLowerInvariant(methodName[0]) + methodName.Substring(1);

    private static string HelperBaseName(QueryContextModel context)
    {
        const string suffix = "SiftQlExtensions";
        return context.HelperName.EndsWith(suffix, StringComparison.Ordinal)
            ? context.HelperName.Substring(0, context.HelperName.Length - suffix.Length)
            : context.InterfaceName;
    }
}
