using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace SiftQL.Generators.Kernel;

internal static class KernelCatalogAttributes
{
    public const string HintName = "SiftQL.KernelCatalogAttributes.g.cs";

    public static SourceText CreateSourceText() => SourceText.From("""
        // <auto-generated />
        #nullable enable
        namespace Microsoft.CodeAnalysis
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.All, Inherited = false)]
            internal sealed class EmbeddedAttribute : global::System.Attribute
            {
            }
        }

        namespace SiftQL
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
            [global::Microsoft.CodeAnalysis.Embedded]
            internal sealed class KernelCatalogAttribute : global::System.Attribute
            {
            }

            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class,
                Inherited = false,
                AllowMultiple = true)]
            [global::Microsoft.CodeAnalysis.Embedded]
            internal sealed class KernelSubjectAttribute : global::System.Attribute
            {
                public KernelSubjectAttribute(global::System.Type subjectType)
                {
                    SubjectType = subjectType;
                }

                public global::System.Type SubjectType { get; }
                public string? Alias { get; set; }
            }
        }
        """, Encoding.UTF8);
}
