using System.Text;

namespace SiftQL.Generators.Kernel;

internal static class KernelCatalogEmitter
{
    public static string Emit(KernelCatalogModel catalog)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        if (!string.IsNullOrEmpty(catalog.NamespaceName))
        {
            source.Append("namespace ");
            source.Append(CSharpIdentifier.EscapePath(catalog.NamespaceName));
            source.AppendLine(";");
            source.AppendLine();
        }

        source.Append(catalog.Accessibility);
        source.Append(" static partial class ");
        source.Append(CSharpIdentifier.EscapePath(catalog.Name));
        source.AppendLine();
        source.AppendLine("{");
        EmitSubjects(source, catalog);
        EmitFor(source);
        EmitKnownSubjectCheck(source, catalog);
        foreach (KernelCatalogSubject subject in catalog.Subjects)
            EmitSubjectFactory(source, subject);
        source.AppendLine("}");
        return source.ToString();
    }

    private static void EmitSubjects(StringBuilder source, KernelCatalogModel catalog)
    {
        source.AppendLine("    private static readonly global::System.Type[] s_subjectTypes =");
        source.AppendLine("    [");
        foreach (KernelCatalogSubject subject in catalog.Subjects)
        {
            source.Append("        typeof(");
            source.Append(subject.TypeName);
            source.AppendLine("),");
        }

        source.AppendLine("    ];");
        source.AppendLine();
        source.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<global::System.Type> SubjectTypes =>");
        source.AppendLine("        s_subjectTypes;");
        source.AppendLine();
    }

    private static void EmitFor(StringBuilder source)
    {
        source.AppendLine("    public static global::SiftQL.QueryKernel<TSubject> For<TSubject>()");
        source.AppendLine("        where TSubject : global::SiftQL.IFilterSubject");
        source.AppendLine("    {");
        source.AppendLine("        if (!IsKnownSubject(typeof(TSubject)))");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::System.ArgumentException(");
        source.AppendLine("                $\"Kernel subject '{typeof(TSubject).FullName ?? typeof(TSubject).Name}' is not registered in this catalog.\",");
        source.AppendLine("                nameof(TSubject));");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        return global::SiftQL.QueryKernel.For<TSubject>();");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void EmitKnownSubjectCheck(StringBuilder source, KernelCatalogModel catalog)
    {
        source.AppendLine("    public static bool IsKnownSubject(global::System.Type subjectType)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(subjectType);");
        foreach (KernelCatalogSubject subject in catalog.Subjects)
        {
            source.Append("        if (subjectType == typeof(");
            source.Append(subject.TypeName);
            source.AppendLine("))");
            source.AppendLine("            return true;");
            source.AppendLine();
        }

        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void EmitSubjectFactory(StringBuilder source, KernelCatalogSubject subject)
    {
        source.Append("    public static global::SiftQL.QueryKernel<");
        source.Append(subject.TypeName);
        source.Append("> ");
        source.Append(CSharpIdentifier.EscapePath(subject.MethodName));
        source.AppendLine("() =>");
        source.Append("        For<");
        source.Append(subject.TypeName);
        source.AppendLine(">();");
        source.AppendLine();
    }
}
