using SiftQL.Generators.Tests;

FilterSchemaSourceGeneratorTests.RunAll();
FilterSchemaGeneratorRegressionTests.RunAll();
FilterSchemaFallbackRegressionTests.RunAll();
FilterSchemaParitySourceGeneratorTests.RunAll();
FilterCompilerCacheRegressionTests.RunAll();
FilterRuntimeRegressionTests.RunAll();
HotProviderNullStringLiteralTests.RunAll();
HotManifestProjectionValidationTests.RunAll();
HotManifestLiteralValidationTests.RunAll();
HotManifestPathStabilityTests.RunAll();
HotManifestIdentityRegressionTests.RunAll();
HotManifestShapeValidationTests.RunAll();
HotProviderFingerprintValidationTests.RunAll();
HotProviderSourceGeneratorTests.RunAll();
HotProviderDuplicateFingerprintTests.RunAll();
HotProviderLoaderLifecycleTests.RunAll();
HotProviderLoaderManifestIsolationTests.RunAll();
HotProviderRegistrationGateTests.RunAll();
HotProviderSemanticValidationTests.RunAll();
HotProviderValidationTests.RunAll();
HotProviderValueCompatibilityTests.RunAll();
KernelCatalogSourceGeneratorTests.RunAll();
KeywordFilterSchemaSourceGeneratorTests.RunAll();
ParameterizedHotProviderSourceGeneratorTests.RunAll();
ProjectionCompilerRuntimeTests.RunAll();
ProjectionDecimalRegressionTests.RunAll();
ProjectionPayloadWriterRegressionTests.RunAll();
ProjectedHotProviderSourceGeneratorTests.RunAll();
RuntimeHotProviderBatchSinkTests.RunAll();
ServerPluginHostExampleTests.RunAll();
TieredProjectionRegressionTests.RunAll();
TieredProviderRecoveryTests.RunAll();
Console.WriteLine("Filter schema generator tests OK");
